import type { Metadata } from "next";
import GuestHeader from "./components/Header/GuestHeader";
import "./globals.css";


export const metadata: Metadata = {
  title: "Estimate app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body>
        <GuestHeader/>
        {children}
      </body>
    </html>
  );
}
